Alert button
nikhil-sharma-nks/Silk-UI pull request #1
Opened 2022-02-05 13:36 UTC by nikhil-sharma-nks

2022-02-06 18:45 UTC, viru2001 requested changes

2022-02-06 18:45 UTC, viru2001 commented on components/alert.html
> +    />
you can import this in your main CSS file

2022-02-06 18:45 UTC, viru2001 commented on components/alert.html
> +              overflow: hidden;
you can make class for this. try to avoid inline styling

2022-02-06 18:45 UTC, viru2001 commented on styles/utilities.css
>    color: #fff;
you can use variable for this

2022-02-06 18:45 UTC, viru2001 commented on styles/utilities.css
> +}
classname and properties mismatched

2022-02-06 18:45 UTC, viru2001 commented on styles/variables.css
> +  --success: #4caf50;
you should use only 1 color unit

2022-02-07 07:57 UTC, saifudinbadani reviewed
add a floating button as well, other wise looks good to merge.

2022-02-07 10:03 UTC, merged